python:
  dockerImage: python:3.7
  scriptInvoker: python

rust:
  dockerImage: rust:1.40
  scriptInvoker: cargo run --manifest-path ./src/rust/Cargo.toml --bin
  envVars: RUST_BACKTRACE=1
  useShortScriptName: true

go:
  dockerImage: golang:1.13
  scriptInvoker: go test
  scriptSuffix: ./src/go/helpers.go

ruby:
  dockerImage: ruby:2.7
  scriptInvoker: ruby

js:
  dockerImage: node:13.5
  scriptInvoker: node
