name: Run Tests

on:
  [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        language: [python, rust]
    name: ${{ matrix.language }}
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v1

      - name: setup rust
        uses: actions/rust-toolchain@v1

      # - if: maxtrix.language == "python"
      #   name: setup python
      #   uses: actions/setup-python@v1

      # - if: maxtrix.language == "rust"
      #   name: setup rust
      #   uses: actions/rust-toolchain@v1
