name: Run Tests

on:
  [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        language: [python, rust]
    name: ${{ matrix.language }}
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        if: matrix.language == 'python'
        uses: actions/setup-python@v1

      - name: setup rust
        if: matrix.language == 'rust'
        uses: actions/rust-toolchain@v1
