name: Run Tests

on:
  [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        language: [python, rust]
    name: ${{ matrix.language }}
    runs-on: ubuntu-latest
    steps:

      - name: Set up python
        if: ${{ maxtrix.language }} == python
        uses: actions/setup-python

      - name: Set up rust
        if: ${{ maxtrix.language }} == rust
        uses: actions/rust-toolchain
