name: Run Tests

on:
  [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        language: [python, rust]
    name: ${{ matrix.language }}
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        if: matrix.language == 'python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: setup rust
        if: matrix.language == 'rust'
        uses: actions-rs/toolchain@v1
        with:
            toolchain: '1.40.0'
            override: true

      - name: run tests
        run: ./scripts/run_tests.sh ${{ matrix.language }}
