name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        language: [python, rust]
    name: ${{ matrix.language }}
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: setup rust
        if: matrix.language == 'rust'
        uses: actions-rs/toolchain@v1
        with:
            toolchain: '1.40.0'
            override: true

      - name: checkout code
        uses: actions/checkout@v2

      - name: install prereqs
        run: |
          pip install pipenv
          pipenv sync

      - name: run tests
        run: pipenv run tests ${{ matrix.language }}
