name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        language: [python, rust, go, ruby, js]
    name: ${{ matrix.language }}
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v1

      - name: checkout code
        uses: actions/checkout@v2

      - name: install prereqs
        run: |
          pip install pipenv
          pipenv sync

      - name: run tests
        run: pipenv run tests ${{ matrix.language }} any first_names
