name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.language }}
    strategy:
      matrix:
        language: [python, rust, go, ruby, js]

    # https://github.com/actions/runner-images
    runs-on: ubuntu-22.04

    steps:
      # https://github.com/actions/setup-python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # https://github.com/actions/checkout
      - name: checkout code
        uses: actions/checkout@v3

      - run: pip install invoke pyyaml
      - run: invoke test ${{ matrix.language }} any
